version: '3'
services:
  postgres:
    container_name: postgres-master
    image: "mdillon/postgis:latest"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    env_file:
      - .env
  back:
    container_name: tile-master
    restart: always
    build: ./tile-server
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    env_file: .env
  front:
    container_name: slide-master
    restart: always
    build: ./slide
    command: npm start
    volumes:
      - ./slide/:/srv/slide/
      - /srv/slide/node_modules
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  pgdata:
