version: '3.5'
services:
  postgres:
    container_name: postgres-master
    image: "mdillon/postgis:latest"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5555:5432"
    env_file:
      - .env
    networks:
      - global
  tile:
    container_name: tile-master
    restart: always
    build: ./tile
    volumes:
      - ./tile/:/srv/tile/
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    env_file: .env
    networks:
      - global
  slide:
    container_name: slide-master
    restart: always
    build: ./slide
    command: npm start
    volumes:
      - ./slide/:/srv/slide/
      - /srv/slide/node_modules
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - global

volumes:
  pgdata:

networks:
  global:
    name: global-network
